services:
  cover-bot:
    build:
      context: .
    environment:
    # CHANGE THESE (or make a .env file which holds these values)
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      COVER_EMAIL: "${COVER_EMAIL}"
      COVER_PASSWORD: "${COVER_PASSWORD}"
      COVER_CHANNEL_ID: "${COVER_CHANNEL_ID}"
      POLL_INTERVAL: "${POLL_INTERVAL:-600}"
      EMBED_IMAGE: "${EMBED_IMAGE}"
    restart: always
